#!/usr/bin/env bash
# run_all.sh -- Demo: Andersen vs Conditional Andersen
# Compares MayAlias counts on 16 small C programs.

set -e
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WPA="$ROOT/SVF/build/bin/wpa"
EXTAPI="$ROOT/SVF/build/lib/extapi.bc"
CODE="$ROOT/demo/code"
BC="$ROOT/demo/bc"
RESULT="$ROOT/demo/result"

mkdir -p "$BC" "$RESULT"

SUMMARY="$RESULT/SUMMARY.md"
{
    echo "# Conditional Andersen Demo Summary"
    echo
    echo "Generated by \`demo/run_all.sh\`. Each cell is the **MayAlias count**."
    echo "'Refined' = ander.MayAlias - condAnder.MayAlias (pairs proven NoAlias)."
    echo
    echo "| Case | -ander | -cond-ander | Refined |"
    echo "|------|--------|-------------|---------|"
} > "$SUMMARY"

count_may () {
    grep -cE "^MayAlias" "$1" || true
}

for src in "$CODE"/*.c; do
    name=$(basename "$src" .c)
    bc="$BC/$name.bc"
    out_a="$RESULT/$name.ander.txt"
    out_c="$RESULT/$name.cond.txt"

    echo "==> $name"
    clang -emit-llvm -c -O0 -g "$src" -o "$bc" 2>/dev/null

    # Vanilla Andersen
    "$WPA" -ander -print-aliases -stat=false -extapi="$EXTAPI" "$bc" > "$out_a" 2>&1 || true
    a_may=$(count_may "$out_a")

    # Conditional Andersen
    "$WPA" -cond-ander -print-aliases -stat=false -extapi="$EXTAPI" "$bc" > "$out_c" 2>&1 || true
    c_may=$(count_may "$out_c")

    refined=$(( a_may - c_may ))
    echo "    ander=$a_may  cond=$c_may  refined=$refined"
    echo "| \`$name\` | $a_may | $c_may | $refined |" >> "$SUMMARY"

    # Diff: alias pairs that changed
    diff_out="$RESULT/$name.diff.txt"
    diff <(grep -E "Alias" "$out_a" | sort) \
         <(grep -E "Alias" "$out_c" | sort) > "$diff_out" || true
done

echo
echo "Done. See $SUMMARY"
